(a)

CREATE VIEW REGISTI_AI_FESTIVAL
SELECT REGISTA, FESTIVAL, COUNT(*) AS NUMERO_PRESENZE
FROM FILM, PARTECIPAZIONE
WHERE CODF = FILM
GROUP BY REGISTA, FESTIVAL

SELECT RF1.REGISTA
FROM REGISTI_AI_FESTIVAL RF1
WHERE RF1.NUMERO_PRESENZE >= ALL (
    SELECT RF2.NUMERO_PRESENZE
    FROM REGISTI_AI_FESTIVAL RF2
    WHERE RF2.FESTIVAL = RF1.FESTIVAL
)

(b)

--trovo tutte le edizioni del Cinema Muto

CREATE VIEW EDIZIONI_CINEMA_MUTO
SELECT FESTIVAL 
FROM PARTECIPAZIONE, FESTIVAL
WHERE NOMEFESTIVAL = FESTIVAL